version: '3.8'

services:
  rejson:
    image: redislabs/rejson:edge
    ports:
      - 6379:6379
    command:
      - redis-server
      - --loadmodule
      - /usr/lib/redis/modules/rejson.so
      - --port
      - '6379'
      - --notify-keyspace-events
      - 'KEA'
